comp_i2c_pkg:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/i2c_pkg/src/i2c_if.sv
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/i2c_pkg/i2c_pkg.sv
comp_common_pkg:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/common_pkg/src/enumtype_i2c.sv

